CREATE TABLE `products` (
  `PRODUCT_ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(255) DEFAULT NULL,
  `PRODUCT_CODE` varchar(255) NOT NULL,
  `PRODUCT_PRICE` int(11) NOT NULL,
  `PRODUCT_DESCRIPTION` longtext NOT NULL,
  `PRODUCT_THUMBNAIL` varchar(255) NOT NULL,
  `PRODUCT_HIDDEN` int(11) NOT NULL,
  `TOTAL_SALES` int(11) NOT NULL,
  `PRODUCT_STOCK` int(11) NOT NULL
